FROM python:3.12

WORKDIR /app

COPY backend/python/requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir --default-timeout=100 -r requirements.txt

COPY backend/python/ .

EXPOSE 5000

CMD ["python", "app.py"]